const fs = require('fs');
const path = require('path');
const packageJson = require('../../package.json');

module.exports = (newVersion) => {

	const versions = {
		xui: newVersion,
		react: packageJson.dependencies.react
	};

	fs.writeFileSync(path.join(__dirname, '..', '..', 'src', 'react', 'components', 'helpers', 'versions.js'),
		`// This file is autogenerated by ~build/version.js and used by the checkXUIVersion.js\n// eslint-disable-next-line quote-props\nexport default ${JSON.stringify(versions)}\n`,
		{encoding: 'utf8'}
	);

}
require('make-runnable/custom')({ printOutputFrame: false });
