const fs = require('fs');
const path = require('path');
const packageJson = require('../../package.json');

module.exports = newVersion => {
  const versions = {
    xui: newVersion || packageJson.version, // Default set as it's used by pre-commit.sh without arguments
    react: packageJson.peerDependencies.react,
  };

  fs.writeFileSync(
    path.join(__dirname, '..', '..', 'src', 'react', 'components', 'helpers', 'versions.js'),
    `// This file is autogenerated by scripts/versions/versions.js and used by the checkXUIVersion.js\n// eslint-disable-next-line\nexport default ${JSON.stringify(
      versions,
    )}\n`,
    { encoding: 'utf8' },
  );
};
require('make-runnable/custom')({ printOutputFrame: false });
