import NOOP from '../../helpers/noop';
import { desktopPlus320 } from '../../../stories/helpers/viewports';

import { sandwichData } from './user-tests';

const storiesWithKnobsKindName = 'Components/XUIEditableTable';
const storiesWithVariationsKindName = `${storiesWithKnobsKindName}/Tests`;
const regressionVariationStoryKindName = `${storiesWithVariationsKindName}/User stories`;

const dragAndDropProps = {
  dndDragCancelledMessage: NOOP,
  dndDragOutsideMessage: NOOP,
  dndDragStartMessage: NOOP,
  dndDragUpdateMessage: NOOP,
  dndDropFailedMessage: NOOP,
  dndDropMessage: NOOP,
  dndInstructions: '',
  onReorderRow: NOOP,
};

const variations = [
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'Default 5 by 5',
    rows: 5,
    columnCount: 5,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'responsive',
    columnCount: 10,
    columnWidths: [
      '60px',
      '80px',
      '100px',
      '120px',
      '80px',
      '100px',
      '120px',
      '60px',
      '80px',
      '100px',
    ],
    hasHeader: true,
    rowOptions: {
      isRemovable: true,
      isDraggable: true,
      removeButtonAriaLabel: 'Remove row',
      dragButtonAriaLabel: 'Reorder row',
    },
    rows: 5,
    renderSmallerWrapper: true,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'responsive with pinned first and last action columns',
    columnCount: 10,
    columnWidths: [
      '60px',
      '80px',
      '100px',
      '120px',
      '80px',
      '100px',
      '120px',
      '60px',
      '80px',
      '100px',
    ],
    hasHeader: true,
    rowOptions: {
      isRemovable: true,
      isDraggable: true,
      removeButtonAriaLabel: 'Remove row',
      dragButtonAriaLabel: 'Reorder row',
    },
    hasPinnedFirstColumn: true,
    hasPinnedLastColumn: true,
    rows: 5,
    renderSmallerWrapper: true,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'responsive with pinned first and last text columns',
    columnCount: 10,
    columnWidths: [
      '60px',
      '80px',
      '100px',
      '120px',
      '80px',
      '100px',
      '120px',
      '60px',
      '80px',
      '100px',
    ],
    hasHeader: true,
    hasPinnedFirstColumn: true,
    hasPinnedLastColumn: true,
    rows: 5,
    renderSmallerWrapper: true,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'responsive with pinned first and last input columns',
    columnCount: 10,
    columnWidths: [
      '60px',
      '80px',
      '100px',
      '120px',
      '80px',
      '100px',
      '120px',
      '60px',
      '80px',
      '100px',
    ],
    cellType: 'textInput',
    hasHeader: true,
    scrollLeft: 20,
    hasPinnedFirstColumn: true,
    hasPinnedLastColumn: true,
    rows: 5,
    renderSmallerWrapper: true,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with a focused cell',
    columnCount: 1,
    cellType: 'textInput',
    clickSelector: 'td',
    rows: 1,
    renderSmallerWrapper: true,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with a focused cell and pinned first column',
    columnCount: 10,
    columnWidths: [
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
    ],
    cellType: 'textInput',
    scrollLeft: 20,
    hasPinnedFirstColumn: true,
    clickSelector: 'td:nth-child(2)',
    rows: 1,
    renderSmallerWrapper: true,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with a focused cell and pinned last column',
    columnCount: 10,
    columnWidths: [
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
      '100px',
    ],
    cellType: 'textInput',
    scrollLeft: 580,
    hasPinnedLastColumn: true,
    clickSelector: 'td:nth-child(9)',
    rows: 1,
    renderSmallerWrapper: true,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with a focused cell and pinned first and last columns',
    columnCount: 3,
    columnWidths: ['100px', '900px', '100px'],
    cellType: 'textInput',
    scrollLeft: 20,
    hasPinnedFirstColumn: true,
    hasPinnedLastColumn: true,
    clickSelector: 'td:nth-child(2)',
    rows: 1,
    renderSmallerWrapper: true,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with max-width smaller than container',
    columnCount: 2,
    columnWidths: ['88px', '88px'],
    hasHeader: true,
    maxWidth: '220px', // 2x 88px + 4px border (2 cols and delete column)
    rowOptions: { isRemovable: true, removeButtonAriaLabel: 'Remove row' },
    rows: 2,
    renderSmallerWrapper: true,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'without max-width',
    columnCount: 2,
    hasHeader: true,
    rowOptions: { isRemovable: true, removeButtonAriaLabel: 'Remove row' },
    rows: 2,
    renderSmallerWrapper: true,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with add new row (button)',
    columnCount: 10,
    columnWidths: ['59px', '59px', '59px', '59px', '59px', '59px', '59px', '59px', '59px', '59px'],
    hasHeader: true,
    rows: 3,
    rowOptions: { isRemovable: true, removeButtonAriaLabel: 'Remove row' },
    renderSmallerWrapper: true,
    showAddRowButton: true,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with footer row',
    columnCount: 4,
    hasHeader: true,
    rows: 3,
    rowOptions: { isRemovable: true, isDraggable: true, removeButtonAriaLabel: 'Remove row' },
    showFooterRow: true,
    maxWidth: '800px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with footer row and actions',
    columnCount: 4,
    hasHeader: true,
    rows: 3,
    rowOptions: { isRemovable: true, isDraggable: true, removeButtonAriaLabel: 'Remove row' },
    showFooterRow: true,
    showAddRowButton: true,
    maxWidth: '800px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'without header',
    columnCount: 4,
    hasHeader: false,
    rowOptions: {
      isRemovable: false,
      isDraggable: false,
      dragButtonAriaLabel: 'Reorder row',
    },
    rows: 5,
    renderSmallerWrapper: true,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with drag and drop, without delete',
    columnCount: 4,
    columnWidths: ['100px', '100px', '100px', 'auto'],
    hasHeader: true,
    rowOptions: {
      isRemovable: false,
      isDraggable: true,
      removeButtonAriaLabel: 'Remove row',
      dragButtonAriaLabel: 'Reorder row',
    },
    rows: 5,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with a single row',
    columnCount: 4,
    columnWidths: ['100px', '100px', '100px', 'auto'],
    hasHeader: true,
    rowOptions: {
      isRemovable: true,
      isDraggable: true,
      removeButtonAriaLabel: 'Remove row',
      dragButtonAriaLabel: 'Reorder row',
    },
    rows: 1,
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with max-width',
    columnCount: 2,
    hasHeader: true,
    rows: 4,
    viewports: desktopPlus320,
    maxWidth: '600px',
    ...dragAndDropProps,
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with min-width and max-width',
    columnCount: 1,
    hasHeader: true,
    rows: 4,
    viewports: desktopPlus320,
    maxWidth: '600px',
    minWidth: '400px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with read-only cells',
    columnCount: 4,
    hasHeader: false,
    rows: 4,
    cellType: 'readOnly',
    withDisabled: true,
    minWidth: '800px',
    maxWidth: '1200px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with text input cells',
    columnCount: 4,
    hasHeader: false,
    rows: 5,
    cellType: 'textInput',
    withDisabled: true,
    maxWidth: '900px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with multiline text input cells',
    columnCount: 4,
    hasHeader: false,
    rows: 5,
    cellType: 'textInputMultiline',
    withDisabled: true,
    maxWidth: '900px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with select cells',
    columnCount: 4,
    hasHeader: false,
    rows: 5,
    cellType: 'selectBox',
    withDisabled: true,
    maxWidth: '900px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with select cell spanning multiple lines',
    columnCount: 2,
    hasHeader: false,
    rows: 1,
    cellType: 'selectBox',
    randomiseContent: true,
    maxWidth: '300px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with autocompleter cells',
    columnCount: 4,
    hasHeader: false,
    rows: 5,
    cellType: 'autoCompleterSingle',
    withDisabled: true,
    maxWidth: '900px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with multi pick autocompleter cells',
    columnCount: 4,
    hasHeader: false,
    rows: 5,
    cellType: 'autoCompleterMulti',
    withDisabled: true,
    maxWidth: '900px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with mixed type cells',
    columnCount: 4,
    hasHeader: false,
    rows: 5,
    cellType: 'assorted',
    maxWidth: '900px',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with invalid and mixed type cells',
    columnCount: 4,
    hasHeader: true,
    rows: 5,
    cellType: 'assorted',
    maxWidth: '900px',
    withInvalid: true,
    validationMessage: 'There was an error.',
  },
  {
    storyKind: storiesWithVariationsKindName,
    storyTitle: 'with end-aligned cells',
    columnCount: 3,
    hasHeader: true,
    rows: 4,
    cellType: 'assorted',
    inlineAlignment: 'end',
  },
];

const regressionVariations = [
  {
    storyKind: regressionVariationStoryKindName,
    storyTitle: 'User test 1',
  },
  {
    storyKind: regressionVariationStoryKindName,
    storyTitle: 'User test 2',
    withDisabled: true,
  },
  {
    storyKind: regressionVariationStoryKindName,
    storyTitle: 'User test 3',
    columnWidths: ['190px', '190px', '160px', '160px', '160px', '250px'],
    items: sandwichData,
  },
  {
    storyKind: regressionVariationStoryKindName,
    storyTitle: 'User test 4',
    columnWidths: ['190px', '190px', '160px', '160px', '160px', '250px'],
    items: sandwichData,
    maxWidth: '800px',
  },
];

export {
  storiesWithVariationsKindName,
  regressionVariationStoryKindName,
  storiesWithKnobsKindName,
  variations,
  regressionVariations,
};
