import React, { Component } from 'react';

class Example extends Component {
  state = {
    navDDisOpen: this.props.navDDisOpen || false,
    searchIsOpen: this.props.searchIsOpen || false,
    poIsOpen: this.props.poIsOpen || false,
  };

  // This is the rendered html of the current navigation, as generated by the SPA boilerplate as of Sept 3, 2021.
  // We will drop it here directly, along with the related stylesheet, for the purposes of testing.
  render() {
    return (
      <>
        <link
          href="https://edge.xero.com/platform/header/5.1.66/header-legacy.min.css"
          rel="stylesheet"
        />
        <div id="shell-nav">
          <header
            className="xrh-header xnav-header xnav-header-business xnav-header-wide"
            data-automationid="xnav-container"
            role="banner"
          >
            <div className="xnav-banner">
              <span className="xnav-banner--text">
                Access tools and advice to help your business through COVID-19.
              </span>
              <a
                className="xnav-banner--action xnav-banner--actionbutton"
                data-event-action="Clicked BANNER_ACTION: banner-covid19-static"
                data-event-category="Nav"
                data-menu-item-type="BANNER_ACTION"
                data-name="banner/banner-covid19-static"
                data-on="click"
                href="https://central.xero.com/s/business-continuity"
                rel="noreferrer"
                target="_blank"
              >
                Go to Xero Central
              </a>
              <button
                aria-label="Dismiss banner"
                className="xnav-header-button xnav-iconbutton xnav-iconbutton-inverted xnav-banner--dismissbutton"
                data-automationid="xnav-banner-dismissButton"
                data-event-action="Clicked BANNER_DISMISS: banner-covid19-static"
                data-event-category="Nav"
                data-on="click"
                title="Dismiss banner"
                type="button"
              >
                <div className="xnav-iconwrapper" role="presentation">
                  <svg
                    className="xnav-icon xnav-icon-svg"
                    focusable="false"
                    height="12"
                    role="presentation"
                    viewBox="0 0 12 12"
                    width="12"
                  >
                    <path d="M6 4.5L10.5 0 12 1.5 7.5 6l4.5 4.5-1.5 1.5L6 7.5 1.5 12 0 10.5 4.5 6 0 1.5 1.5 0 6 4.5z" />
                  </svg>
                </div>
              </button>
            </div>
            <div className="xnav-header--main">
              <div
                className="xnav-appmenucontainer"
                data-header-component="menu-parent"
                tabIndex="-1"
              >
                <button
                  aria-haspopup="true"
                  className="xnav-header-button xnav-appbutton"
                  data-automationid="xnav-appbutton"
                  data-header-component="menu-trigger"
                  // eslint-disable-next-line react/no-access-state-in-setstate
                  onClick={() => this.setState({ navDDisOpen: !this.state.navDDisOpen })}
                  type="button"
                >
                  <div className="xnav-appbutton--body">
                    <span className="xnav-appbutton--text">Test Practice NZ</span>
                    <svg
                      className="xnav-appbutton--caret xnav-icon xnav-icon-svg"
                      focusable="false"
                      height="5"
                      role="presentation"
                      viewBox="0 0 10 5"
                      width="10"
                    >
                      <path d="M0 0l5 5 5-5z" />
                    </svg>
                  </div>
                </button>
                <div
                  aria-hidden="false"
                  className="xnav-appmenu xnav-appmenu- xnav-appmenu-wide"
                  data-header-component="menu"
                >
                  <div className="xnav-appmenu--mask xnav-appmenu--mask-is-active" />
                  <div
                    className={`xnav-appmenu--body  xnav-appmenu--body-downshift-for-banner ${
                      this.state.navDDisOpen && 'xnav-appmenu--body-is-open'
                    }`}
                    tabIndex="-1"
                  >
                    <div className="xnav-appmenuheader">
                      <abbr
                        className="xnav-avatar xnav-avatar-large xnav-avatar-color-6 xnav-avatar-business"
                        role="presentation"
                      >
                        TPN
                      </abbr>
                      <div className="xnav-appmenu--headings">
                        <span className="xnav-appmenu--heading" title="Test Practice NZ">
                          Test Practice NZ
                        </span>
                        <span className="xnav-appmenu--subheading" />
                      </div>
                    </div>
                    <hr className="xnav-divider" />
                    <div>
                      <ol className="xnav-verticalmenu" role="navigation">
                        <li className="xnav-verticalmenuitem">
                          <a
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked APP_MENU: files"
                            data-event-category="Nav"
                            data-menu-item-type="APP_MENU"
                            data-name="application-menu/xero/files"
                            data-on="click"
                            href="https://go.xero.com/Docs/Folders"
                            tabIndex="-1"
                          >
                            Files
                          </a>
                        </li>
                        <li className="xnav-verticalmenuitem">
                          <a
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked APP_MENU: org-settings"
                            data-event-category="Nav"
                            data-menu-item-type="APP_MENU"
                            data-name="application-menu/xero/org-settings"
                            data-on="click"
                            href="https://go.xero.com/Settings/OrganisationSettings/"
                            tabIndex="-1"
                          >
                            Settings
                          </a>
                        </li>
                      </ol>
                    </div>
                    <hr className="xnav-divider" />
                    <div aria-busy="false">
                      <ol
                        aria-describedby="xnav-heading-orgs"
                        className="xnav-verticalmenu"
                        role="navigation"
                      >
                        <li className="xnav-verticalmenuitem xnav-verticalmenuitem-lefticon">
                          <div className="xnav-verticalmenuitem--icon xnav-iconwrapper">
                            <abbr
                              className="xnav-avatar xnav-avatar-small xnav-avatar-color-9 xnav-avatar-business"
                              role="presentation"
                            >
                              DC
                            </abbr>
                          </div>
                          <a
                            className="xnav-verticalmenuitem--body xnav-menuitem-orgpractice"
                            data-event-action="Clicked ORG"
                            data-event-category="Nav"
                            data-menu-item-type="ORG"
                            data-name="demo-company"
                            data-on="click"
                            href="https://my.xero.com/!xkcD/Dashboard/DemoOrganisation/CreateDemoAndLogin"
                            tabIndex="-1"
                            title="demo-company"
                          >
                            Demo Company
                          </a>
                        </li>
                        <li className="xnav-verticalmenuitem xnav-verticalmenuitem-lefticon">
                          <div className="xnav-verticalmenuitem--icon xnav-iconwrapper">
                            <div className="xnav-orglinkadd">
                              <svg
                                className="xnav-icon xnav-icon-svg"
                                focusable="false"
                                height="12"
                                role="presentation"
                                viewBox="0 0 12 12"
                                width="12"
                              >
                                <path d="M7 5h5v2H7v5H5V7H0V5h5V0h2v5z" />
                              </svg>
                            </div>
                          </div>
                          <a
                            className="xnav-verticalmenuitem--body xnav-verticalmenuitem--body-blue"
                            data-event-action="Clicked ADD_NEW_ORG"
                            data-event-category="Nav"
                            data-menu-item-type="ADD_NEW_ORG"
                            data-name="organisation-menu/add-organisation-for-practice"
                            data-on="click"
                            href="https://my.xero.com/!XGDbx/Organisation/Add"
                            tabIndex="-1"
                          >
                            Add a new organisation
                          </a>
                        </li>
                      </ol>
                    </div>
                    <hr className="xnav-divider" />
                    <div>
                      <span className="xnav-verticalmenu--heading">Do more with Xero</span>
                      <ol
                        aria-label="Do more with Xero"
                        className="xnav-verticalmenu"
                        role="navigation"
                      >
                        <li className="xnav-verticalmenuitem">
                          <a
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked APP_MENU_GROUP: promo-projects"
                            data-event-category="Nav"
                            data-menu-item-type="APP_MENU_GROUP"
                            data-name="application-menu/xero/do-more-with-xero/promo-projects"
                            data-on="click"
                            href="https://go.xero.com/app/!XGDbx/projects/"
                            tabIndex="-1"
                          >
                            Projects
                          </a>
                        </li>
                        <li className="xnav-verticalmenuitem xnav-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xnav-access-opens-new-window"
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked APP_MENU_GROUP: promo-workflowmax"
                            data-event-category="Nav"
                            data-menu-item-type="APP_MENU_GROUP"
                            data-name="application-menu/xero/do-more-with-xero/promo-workflowmax"
                            data-on="click"
                            href="https://my.workflowmax.com/"
                            rel="nofollow noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            WorkflowMax
                          </a>
                          <div className="xnav-verticalmenuitem--icon xnav-verticalmenuitem--icon-right xnav-iconwrapper">
                            <svg
                              className="xnav-icon xnav-icon-svg"
                              focusable="false"
                              height="12"
                              role="presentation"
                              viewBox="0 0 12 12"
                              width="12"
                            >
                              <path d="M10.75 2.75L7 6.5 5.5 5l3.75-3.75L8 0h4v4l-1.25-1.25zM6 0v1H1v10h10V6h1v4.91c0 .545-.5 1.09-1 1.09H1c-.5 0-1-.545-1-1.09l.01-9.82C0 .546.5 0 1 0h5z" />
                            </svg>
                          </div>
                        </li>
                        <li className="xnav-verticalmenuitem xnav-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xnav-access-opens-new-window"
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked APP_MENU_GROUP: hubdoc"
                            data-event-category="Nav"
                            data-menu-item-type="APP_MENU_GROUP"
                            data-name="application-menu/xero/do-more-with-xero/hubdoc"
                            data-on="click"
                            href="https://app.hubdoc.com/"
                            rel="nofollow noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            Hubdoc
                          </a>
                          <div className="xnav-verticalmenuitem--icon xnav-verticalmenuitem--icon-right xnav-iconwrapper">
                            <svg
                              className="xnav-icon xnav-icon-svg"
                              focusable="false"
                              height="12"
                              role="presentation"
                              viewBox="0 0 12 12"
                              width="12"
                            >
                              <path d="M10.75 2.75L7 6.5 5.5 5l3.75-3.75L8 0h4v4l-1.25-1.25zM6 0v1H1v10h10V6h1v4.91c0 .545-.5 1.09-1 1.09H1c-.5 0-1-.545-1-1.09l.01-9.82C0 .546.5 0 1 0h5z" />
                            </svg>
                          </div>
                        </li>
                        <li className="xnav-verticalmenuitem">
                          <a
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked APP_MENU_GROUP: app-store"
                            data-event-category="Nav"
                            data-menu-item-type="APP_MENU_GROUP"
                            data-name="application-menu/xero/do-more-with-xero/app-store"
                            data-on="click"
                            href="https://apps.xero.com/login"
                            tabIndex="-1"
                          >
                            App Store
                          </a>
                        </li>
                      </ol>
                    </div>
                    <hr className="xnav-divider" />
                    <div className="xnav-appmenu--otherapps">
                      <ol className="xnav-verticalmenu" role="navigation">
                        <li className="xnav-verticalmenuitem xnav-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xnav-access-opens-new-window"
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked OTHER_APP: xero-hq"
                            data-event-category="Nav"
                            data-menu-item-type="OTHER_APP"
                            data-name="partner-apps-menu/xero-hq"
                            data-on="click"
                            href="https://hq.xero.com/"
                            rel="nofollow noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            Xero HQ
                          </a>
                          <div className="xnav-verticalmenuitem--icon xnav-verticalmenuitem--icon-right xnav-iconwrapper">
                            <svg
                              className="xnav-icon xnav-icon-svg"
                              focusable="false"
                              height="12"
                              role="presentation"
                              viewBox="0 0 12 12"
                              width="12"
                            >
                              <path d="M10.75 2.75L7 6.5 5.5 5l3.75-3.75L8 0h4v4l-1.25-1.25zM6 0v1H1v10h10V6h1v4.91c0 .545-.5 1.09-1 1.09H1c-.5 0-1-.545-1-1.09l.01-9.82C0 .546.5 0 1 0h5z" />
                            </svg>
                          </div>
                        </li>
                        <li className="xnav-verticalmenuitem xnav-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xnav-access-opens-new-window"
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked OTHER_APP: my-xero"
                            data-event-category="Nav"
                            data-menu-item-type="OTHER_APP"
                            data-name="partner-apps-menu/my-xero"
                            data-on="click"
                            href="https://my.xero.com/"
                            rel="nofollow noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            My Xero
                          </a>
                          <div className="xnav-verticalmenuitem--icon xnav-verticalmenuitem--icon-right xnav-iconwrapper">
                            <svg
                              className="xnav-icon xnav-icon-svg"
                              focusable="false"
                              height="12"
                              role="presentation"
                              viewBox="0 0 12 12"
                              width="12"
                            >
                              <path d="M10.75 2.75L7 6.5 5.5 5l3.75-3.75L8 0h4v4l-1.25-1.25zM6 0v1H1v10h10V6h1v4.91c0 .545-.5 1.09-1 1.09H1c-.5 0-1-.545-1-1.09l.01-9.82C0 .546.5 0 1 0h5z" />
                            </svg>
                          </div>
                        </li>
                        <li className="xnav-verticalmenuitem xnav-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xnav-access-opens-new-window"
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked OTHER_APP: workpapers"
                            data-event-category="Nav"
                            data-menu-item-type="OTHER_APP"
                            data-name="partner-apps-menu/workpapers"
                            data-on="click"
                            href="https://workpapers.xero.com/"
                            rel="nofollow noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            Workpapers
                          </a>
                          <div className="xnav-verticalmenuitem--icon xnav-verticalmenuitem--icon-right xnav-iconwrapper">
                            <svg
                              className="xnav-icon xnav-icon-svg"
                              focusable="false"
                              height="12"
                              role="presentation"
                              viewBox="0 0 12 12"
                              width="12"
                            >
                              <path d="M10.75 2.75L7 6.5 5.5 5l3.75-3.75L8 0h4v4l-1.25-1.25zM6 0v1H1v10h10V6h1v4.91c0 .545-.5 1.09-1 1.09H1c-.5 0-1-.545-1-1.09l.01-9.82C0 .546.5 0 1 0h5z" />
                            </svg>
                          </div>
                        </li>
                        <li className="xnav-verticalmenuitem xnav-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xnav-access-opens-new-window"
                            className="xnav-verticalmenuitem--body"
                            data-event-action="Clicked OTHER_APP: practice-manager-tax"
                            data-event-category="Nav"
                            data-menu-item-type="OTHER_APP"
                            data-name="partner-apps-menu/practice-manager-tax"
                            data-on="click"
                            href="https://practicemanager.xero.com/"
                            rel="nofollow noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            Practice Manager &amp; Tax
                          </a>
                          <div className="xnav-verticalmenuitem--icon xnav-verticalmenuitem--icon-right xnav-iconwrapper">
                            <svg
                              className="xnav-icon xnav-icon-svg"
                              focusable="false"
                              height="12"
                              role="presentation"
                              viewBox="0 0 12 12"
                              width="12"
                            >
                              <path d="M10.75 2.75L7 6.5 5.5 5l3.75-3.75L8 0h4v4l-1.25-1.25zM6 0v1H1v10h10V6h1v4.91c0 .545-.5 1.09-1 1.09H1c-.5 0-1-.545-1-1.09l.01-9.82C0 .546.5 0 1 0h5z" />
                            </svg>
                          </div>
                        </li>
                      </ol>
                    </div>
                  </div>
                </div>
              </div>
              <div className="xnav-u-hidden xnav-pagetitlewrapper">
                <span className="xnav-pagetitle" data-automationid="xnav-pagetitle" />
              </div>
              <ol
                className="xnav-tabgroup xnav-tabgroup-layout xnav-navigation xnav-header-background-color"
                role="navigation"
              >
                <li className="xnav-tab" data-header-component="menu-parent" tabIndex="-1">
                  <a
                    className="xnav-focusable xnav-tab--body"
                    data-event-action="Clicked NAVIGATION: dashboard"
                    data-event-category="Nav"
                    data-header-component="menu-trigger"
                    data-menu-item-type="NAVIGATION"
                    data-name="navigation-menu/dashboard"
                    data-on="click"
                    href="https://go.xero.com/Dashboard"
                    tabIndex="0"
                  >
                    Dashboard
                  </a>
                </li>
                <li className="xnav-tab" data-header-component="menu-parent" tabIndex="-1">
                  <button
                    aria-haspopup="true"
                    className="xnav-focusable xnav-tab--body"
                    data-event-action="Clicked NAVIGATION: business"
                    data-event-category="Nav"
                    data-header-component="menu-trigger"
                    data-menu-item-type="NAVIGATION"
                    data-name="navigation-menu/business"
                    data-on="click"
                    tabIndex="0"
                    type="button"
                  >
                    Business
                  </button>
                </li>
                <li className="xnav-tab" data-header-component="menu-parent" tabIndex="-1">
                  <button
                    aria-haspopup="true"
                    className="xnav-focusable xnav-tab--body"
                    data-event-action="Clicked NAVIGATION: accounting"
                    data-event-category="Nav"
                    data-header-component="menu-trigger"
                    data-menu-item-type="NAVIGATION"
                    data-name="navigation-menu/accounting"
                    data-on="click"
                    // eslint-disable-next-line react/no-access-state-in-setstate
                    onClick={() => this.setState({ navDDisOpen: !this.state.navDDisOpen })}
                    tabIndex="0"
                    type="button"
                  >
                    Accounting
                  </button>
                  <div
                    aria-hidden="true"
                    className={`xnav-dropdown-layout xnav-nav--dropdown xnav-dropdown-positionleft ${
                      this.state.navDDisOpen && 'xnav-dropdown-is-open'
                    }`}
                    data-header-component="menu"
                  >
                    <div className="xnav-dropdown--mask" />
                    <div
                      aria-hidden="true"
                      className="xnav-dropdown--panel"
                      role="listbox"
                      tabIndex="-1"
                    >
                      <div className="xnav-dropdown--body">
                        <ol className="xnav-verticalmenu" role="navigation">
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: bank-accounts"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="navigation-menu/accounting/bank-accounts"
                              data-on="click"
                              href="https://go.xero.com/Bank/BankAccounts.aspx"
                              tabIndex="-1"
                            >
                              Bank accounts
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: reports"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="navigation-menu/accounting/reports"
                              data-on="click"
                              href="https://reporting.xero.com/!XGDbx"
                              tabIndex="-1"
                            >
                              Reports
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: advanced"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="navigation-menu/accounting/advanced"
                              data-on="click"
                              href="https://go.xero.com/Settings/AdvancedAccounting"
                              tabIndex="-1"
                            >
                              Advanced
                            </a>
                          </li>
                        </ol>
                        <hr className="xnav-divider" />
                        <span className="xnav-verticalmenu--heading">
                          <svg
                            className="xnav-icon-favourites xnav-icon xnav-icon-svg"
                            focusable="false"
                            height="15"
                            role="presentation"
                            viewBox="0 0 15 15"
                            width="15"
                          >
                            <path d="M7.5 12.5l-5 2.5.833-5.417L0 5.833 5 5l2.5-5L10 5l5 .833-3.333 3.75L12.5 15z" />
                          </svg>
                          Reports
                        </span>
                        <ol aria-label="Reports" className="xnav-verticalmenu" role="navigation">
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: report-AgedPayables"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="f3dc0445-c702-4fcf-a893-04359c156831"
                              data-on="click"
                              href="https://reporting.xero.com/!XGDbx/v2/Run/New/f3dc0445-c702-4fcf-a893-04359c156831"
                              tabIndex="-1"
                            >
                              Aged Payables
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: report-AgedReceivables"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="6abd4259-b811-4ba6-a7c0-df1784d5c83d"
                              data-on="click"
                              href="https://reporting.xero.com/!XGDbx/v2/Run/New/6abd4259-b811-4ba6-a7c0-df1784d5c83d"
                              tabIndex="-1"
                            >
                              Aged Receivables
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: report-BalanceSheet"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="9ca7824b-6a38-4a4e-ac38-cae342b2d049"
                              data-on="click"
                              href="https://reporting.xero.com/!XGDbx/v2/Run/New/9ca7824b-6a38-4a4e-ac38-cae342b2d049"
                              tabIndex="-1"
                            >
                              Balance Sheet
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: report-CashSummary"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="6ea3fdc4-c59c-41c4-b9fe-0a7b6a36c376"
                              data-on="click"
                              href="https://reporting.xero.com/!XGDbx/v2/Run/New/6ea3fdc4-c59c-41c4-b9fe-0a7b6a36c376"
                              tabIndex="-1"
                            >
                              Cash Summary
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: report-GSTReturn"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="55272e30-5392-48aa-b366-a34b9b1cfbf6"
                              data-on="click"
                              href="https://reporting.xero.com/!XGDbx/v2/Run/New/55272e30-5392-48aa-b366-a34b9b1cfbf6"
                              tabIndex="-1"
                            >
                              GST Return
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: report-ProfitandLoss"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="a22c12ce-7b22-49ff-a674-1a509552f6de"
                              data-on="click"
                              href="https://reporting.xero.com/!XGDbx/v2/Run/New/a22c12ce-7b22-49ff-a674-1a509552f6de"
                              tabIndex="-1"
                            >
                              Profit and Loss
                            </a>
                          </li>
                        </ol>
                        <hr className="xnav-divider" />
                        <span className="xnav-verticalmenu--heading">
                          <svg
                            className="xnav-icon-favourites xnav-icon xnav-icon-svg"
                            focusable="false"
                            height="15"
                            role="presentation"
                            viewBox="0 0 15 15"
                            width="15"
                          >
                            <path d="M7.5 12.5l-5 2.5.833-5.417L0 5.833 5 5l2.5-5L10 5l5 .833-3.333 3.75L12.5 15z" />
                          </svg>
                          Advanced
                        </span>
                        <ol aria-label="Advanced" className="xnav-verticalmenu" role="navigation">
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: settings-favourite-CHARTOFACCOUNTS"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="chart-of-accounts"
                              data-on="click"
                              href="https://go.xero.com/GeneralLedger/ChartOfAccounts.aspx"
                              tabIndex="-1"
                            >
                              Chart of accounts
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: settings-favourite-TOOLS_FIND"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="find-and-recode"
                              data-on="click"
                              href="https://go.xero.com/Accounts/Recoding"
                              tabIndex="-1"
                            >
                              Find and recode
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: settings-favourite-TOOLS_FIXEDASSETS"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="fixed-assets"
                              data-on="click"
                              href="https://fixedassets.xero.com/?CID=!XGDbx#assets"
                              tabIndex="-1"
                            >
                              Fixed assets
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked NAVIGATION_SUBMENU: settings-favourite-TOOLS_JOURNALS"
                              data-event-category="Nav"
                              data-menu-item-type="NAVIGATION_SUBMENU"
                              data-name="manual-journals"
                              data-on="click"
                              href="https://go.xero.com/Journal/Search.aspx"
                              tabIndex="-1"
                            >
                              Manual journals
                            </a>
                          </li>
                        </ol>
                      </div>
                    </div>
                  </div>
                </li>
                <li className="xnav-tab" data-header-component="menu-parent" tabIndex="-1">
                  <button
                    aria-haspopup="true"
                    className="xnav-focusable xnav-tab--body"
                    data-event-action="Clicked NAVIGATION: payroll"
                    data-event-category="Nav"
                    data-header-component="menu-trigger"
                    data-menu-item-type="NAVIGATION"
                    data-name="navigation-menu/payroll"
                    data-on="click"
                    tabIndex="0"
                    type="button"
                  >
                    Payroll
                  </button>
                </li>
                <li className="xnav-tab" data-header-component="menu-parent" tabIndex="-1">
                  <button
                    aria-haspopup="true"
                    className="xnav-focusable xnav-tab--body"
                    data-event-action="Clicked NAVIGATION: contacts"
                    data-event-category="Nav"
                    data-header-component="menu-trigger"
                    data-menu-item-type="NAVIGATION"
                    data-name="navigation-menu/contacts"
                    data-on="click"
                    tabIndex="0"
                    type="button"
                  >
                    Contacts
                  </button>
                </li>
              </ol>
              <ol className="xnav-addons xnav-header-background-color">
                <li
                  className="xnav-addon"
                  data-automationid="xrh-addon-quicklaunch"
                  data-header-component="menu-parent"
                  tabIndex="-1"
                >
                  <button
                    aria-haspopup="true"
                    aria-label="Quick Launch"
                    className="xnav-header-button xnav-addon--iconbutton xnav-header--iconbutton xnav-focusable--parent"
                    data-automationid="xrh-addon-quicklaunch-iconbutton"
                    data-header-component="menu-trigger"
                    title="Quick Launch"
                    type="button"
                  >
                    <div className="xnav-focusable--child xnav-iconwrapper" role="presentation">
                      <svg
                        className="xnav-icon xnav-icon-svg"
                        focusable="false"
                        height="12"
                        role="presentation"
                        viewBox="0 0 12 12"
                        width="12"
                      >
                        <path d="M7 5h5v2H7v5H5V7H0V5h5V0h2v5z" />
                      </svg>
                    </div>
                  </button>
                </li>
                <li
                  className="xnav-addon"
                  data-automationid="xrh-addon-search"
                  data-header-component="menu-parent"
                  tabIndex="-1"
                >
                  <button
                    aria-haspopup="true"
                    aria-label="Search"
                    className="xnav-header-button xnav-addon--iconbutton xnav-header--iconbutton xnav-focusable--parent"
                    data-automationid="xrh-addon-search-iconbutton"
                    data-header-component="menu-trigger"
                    // eslint-disable-next-line react/no-access-state-in-setstate
                    onClick={() => this.setState({ searchIsOpen: !this.state.searchIsOpen })}
                    tabIndex="0"
                    title="Search"
                    type="button"
                  >
                    <div className="xnav-focusable--child xnav-iconwrapper" role="presentation">
                      <svg
                        className="xnav-icon xnav-icon-svg"
                        focusable="false"
                        height="15"
                        role="presentation"
                        viewBox="0 0 15 15"
                        width="15"
                      >
                        <path d="M11.019 9.588L15 13.57 13.57 15l-3.982-3.981a6.048 6.048 0 0 1-3.519 1.12A6.061 6.061 0 0 1 0 6.069 6.061 6.061 0 0 1 6.07 0a6.061 6.061 0 0 1 6.069 6.07 6.048 6.048 0 0 1-1.12 3.518zm-4.95 1.033a4.546 4.546 0 0 0 4.552-4.552A4.546 4.546 0 0 0 6.07 1.517 4.546 4.546 0 0 0 1.517 6.07a4.546 4.546 0 0 0 4.552 4.552z" />
                      </svg>
                    </div>
                  </button>
                  <div
                    data-automationid="xrh-addon-search-body"
                    data-header-component="menu"
                    tabIndex="-1"
                  >
                    <iframe
                      frameBorder="0"
                      id="GlobalSearchApp"
                      scrolling="no"
                      style={{
                        position: 'absolute',
                        backgroundColor: '#f2f3f4',
                        display: this.state.searchIsOpen ? 'block' : 'none',
                        width: '350px',
                        height: '63px',
                        zIndex: 100,
                        right: '-10px',
                        top: '40px',
                      }}
                      title="Global Search"
                    />
                  </div>
                </li>
                <li
                  className="xnav-addon"
                  data-automationid="xrh-addon-postoffice"
                  data-header-component="menu-parent"
                  tabIndex="-1"
                >
                  <button
                    aria-haspopup="true"
                    aria-label="Post Office"
                    className="xnav-header-button xnav-addon--iconbutton xnav-header--iconbutton xnav-focusable--parent"
                    data-automationid="xrh-addon-postoffice-iconbutton"
                    data-header-component="menu-trigger"
                    // eslint-disable-next-line react/no-access-state-in-setstate
                    onClick={() => this.setState({ poIsOpen: !this.state.poIsOpen })}
                    title="Post Office"
                    type="button"
                  >
                    <div className="xnav-focusable--child xnav-iconwrapper" role="presentation">
                      <svg
                        className="xnav-icon xnav-icon-svg"
                        focusable="false"
                        height="15"
                        role="presentation"
                        viewBox="0 0 13 15"
                        width="13"
                      >
                        <path d="M8 13.5H5c0 2 3 2 3 0zm3-4v-3c0-3-2.044-4-3.044-4v-1c0-2-2.926-2-2.926 0v1c-1 0-3.03 1-3.03 4v3l-2 2v1h13v-1l-2-2z" />
                      </svg>
                    </div>
                  </button>
                  <div
                    data-automationid="xrh-addon-postoffice-body"
                    data-header-component="menu"
                    tabIndex="-1"
                  >
                    <div
                      className="po-addonvisual-dropdownwrapper"
                      style={{ color: '#000a1e', position: 'relative' }}
                    >
                      <div
                        aria-hidden="true"
                        className="xui-dropdown--panel"
                        role="presentation"
                        tabIndex="-1"
                      >
                        <div
                          className={`xui-dropdown--body xrh-addon--dropdown po-addonvisual-dropdownpanel xui-dropdown-layout ${
                            !this.state.poIsOpen && 'xui-u-hidden'
                          }`}
                          role="presentation"
                          style={{
                            position: 'absolute',
                            right: 0,
                            top: '5px',
                            width: '400px',
                            zIndex: 3000,
                          }}
                        >
                          <div
                            className="po-addonvisual-dropdownheader"
                            style={{
                              display: 'flex',
                              justifyContent: 'space-between',
                              alignItems: 'center',
                            }}
                          >
                            <div className="xui-dropdown--header">
                              <div
                                className="xui-dropdown--header-container"
                                style={{
                                  alignItems: 'center',
                                  boxShadow: '0 1px 0 0 rgb(0 10 30 / 20%)',
                                  display: 'flex',
                                  justifyContent: 'space-between',
                                  padding: '12px',
                                  width: '100%',
                                }}
                              >
                                <div
                                  className="xui-dropdown--header-leftcontent"
                                  style={{
                                    alignItems: 'center',
                                    display: 'flex',
                                    flex: 1,
                                    overflow: 'hidden',
                                    paddingRight: '8px',
                                  }}
                                >
                                  <div className="xui-heading-medium xui-margin-left-2xsmall xui-text-truncated">
                                    Notifications
                                  </div>
                                </div>
                              </div>
                            </div>
                            <button
                              aria-label="Archive this"
                              className="xui-button xui-button-icon-medium xui-button-icon"
                              tabIndex="0"
                              type="button"
                            >
                              <svg
                                className="xui-icon"
                                focusable="false"
                                height="12"
                                viewBox="0 0 12 12"
                                width="12"
                              >
                                <path
                                  d="M6 4.5L10.5 0 12 1.5 7.5 6l4.5 4.5-1.5 1.5L6 7.5 1.5 12 0 10.5 4.5 6 0 1.5 1.5 0 6 4.5z"
                                  role="presentation"
                                />
                              </svg>
                              <div className="xui-touchtarget" />
                            </button>
                          </div>
                          <div className="xui-dropdown--scrollable-container">
                            <div className="xui-dropdown--scrollable-content">
                              <div className="xui-panel-background">
                                <div className="xui-autocompleter--emptystate">
                                  <div className="xui-iconwrapper xui-iconwrapper-large">
                                    <svg
                                      className="xui-icon"
                                      focusable="false"
                                      height="13.333333333333332"
                                      viewBox="0 0 13 10"
                                      width="17.333333333333332"
                                    >
                                      <path
                                        d="M0 5.714l1.444-1.428 2.89 2.857L11.555 0 13 1.429 4.333 10z"
                                        role="presentation"
                                      />
                                    </svg>
                                  </div>
                                  No notifications
                                </div>
                                <div data-automationid="notification-cards-high_priority" />
                                <div data-automationid="notification-cards-normal_priority" />
                              </div>
                            </div>
                            <div className="xui-dropdown--footer xui-dropdown--footer-layout">
                              <div className="xui-actions xui-actions-layout xui-actions-linear">
                                <button
                                  className="xui-button xui-actions--primary xui-button-borderless-muted xui-button-medium xui-button-is-disabled"
                                  data-automationid="xui-markAllAsRead"
                                  disabled=""
                                  tabIndex="-1"
                                  type="button"
                                >
                                  Mark all as read
                                </button>
                                <button
                                  className="xui-button xui-actions--secondary xui-button-borderless-main xui-button-medium"
                                  data-automationid="settings"
                                  tabIndex="0"
                                  type="button"
                                >
                                  Settings
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        aria-hidden="true"
                        className="xui-mask xui-modal-mask xui-unmask"
                        role="presentation"
                      >
                        <section
                          aria-labelledby="xui-settings-modal-header-id"
                          className="xui-modal xui-modal-width-medium xui-modal-layout"
                          tabIndex="-1"
                        >
                          <header
                            className="xui-modal--header xui-modal--heading"
                            id="xui-settings-modal-header-id"
                          >
                            Notification settings
                            <button
                              aria-label="Close"
                              className="xui-button xui-modal--close xui-button-icon-medium xui-button-icon"
                              tabIndex="0"
                              title="Close"
                              type="button"
                            >
                              <svg
                                className="xui-icon"
                                focusable="false"
                                height="12"
                                viewBox="0 0 12 12"
                                width="12"
                              >
                                <path
                                  d="M6 4.5L10.5 0 12 1.5 7.5 6l4.5 4.5-1.5 1.5L6 7.5 1.5 12 0 10.5 4.5 6 0 1.5 1.5 0 6 4.5z"
                                  role="presentation"
                                />
                              </svg>
                              <div className="xui-touchtarget" />
                            </button>
                          </header>
                          <div className="xui-modal--body">
                            <div className="xui-full-width-switch xui-switchwrapper xui-switch-medium">
                              <label
                                className="xui-switch xui-switch-reversed"
                                data-automationid="preferenceCheckbox"
                                role="presentation"
                              >
                                <input
                                  aria-checked="false"
                                  aria-labelledby="xui-settings-modal-switch-id"
                                  className="xui-switch--checkbox"
                                  data-automationid="preferenceCheckbox--input"
                                  role="switch"
                                  type="checkbox"
                                />
                                <div
                                  className="xui-switch--control xui-switch--control-medium"
                                  data-automationid="preferenceCheckbox--switch"
                                >
                                  <div className="xui-touchtarget" />
                                </div>
                                <span
                                  className="xui-switch--label xui-switch--label-medium"
                                  data-automationid="preferenceCheckbox--label"
                                  id="xui-settings-modal-switch-id"
                                >
                                  Show notification pop-ups
                                </span>
                              </label>
                            </div>
                          </div>
                          <footer className="xui-modal--footer">
                            <div className="xui-actions xui-actions-layout">
                              <button
                                className="xui-button xui-actions--primary xui-button-main xui-button-medium"
                                data-automationid="savePreferences"
                                tabIndex="0"
                                type="button"
                              >
                                Save
                              </button>
                              <button
                                className="xui-button xui-actions--secondary xui-button-standard xui-button-medium"
                                data-automationid="closePreferences"
                                tabIndex="0"
                                type="button"
                              >
                                Cancel
                              </button>
                            </div>
                          </footer>
                        </section>
                      </div>
                    </div>
                  </div>
                </li>
                <li
                  className="xnav-addon"
                  data-automationid="xrh-addon-help"
                  data-header-component="menu-parent"
                  tabIndex="-1"
                >
                  <button
                    aria-haspopup="true"
                    aria-label="Help"
                    className="xnav-header-button xnav-addon--iconbutton xnav-header--iconbutton xnav-focusable--parent"
                    data-automationid="xrh-addon-help-iconbutton"
                    data-header-component="menu-trigger"
                    title="Help"
                    type="button"
                  >
                    <div className="xnav-focusable--child xnav-iconwrapper" role="presentation">
                      <svg
                        className="xnav-icon xnav-icon-svg"
                        focusable="false"
                        height="15"
                        role="presentation"
                        viewBox="0 0 15 15"
                        width="15"
                      >
                        <path d="M7.5 15a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15zm-.991-5.002V12H8.55V9.998H6.509zm-2.093-4.29h1.911c0-.234.026-.453.078-.657a1.58 1.58 0 0 1 .24-.532c.109-.152.247-.273.417-.365.169-.09.37-.136.604-.136.347 0 .617.095.813.286.195.19.292.485.292.884.009.234-.032.429-.123.585-.092.156-.21.299-.358.429-.147.13-.308.26-.481.39s-.338.284-.494.462a2.686 2.686 0 0 0-.41.643c-.117.251-.188.563-.214.936v.585h1.755v-.494c.035-.26.12-.477.254-.65.134-.173.288-.327.461-.462.173-.134.357-.268.553-.402a2.532 2.532 0 0 0 .936-1.176c.108-.27.162-.612.162-1.028a2.333 2.333 0 0 0-.702-1.625c-.251-.251-.583-.461-.994-.63-.412-.17-.926-.254-1.541-.254-.477 0-.908.08-1.293.24a2.87 2.87 0 0 0-.989.67 3.053 3.053 0 0 0-.636 1.014c-.152.39-.232.819-.241 1.287z" />
                      </svg>
                    </div>
                  </button>
                  <div
                    data-automationid="xrh-addon-help-body"
                    data-header-component="menu"
                    tabIndex="-1"
                  >
                    <div className="nhm-container nhm-addonvisual-dropdownwrapper">
                      <div
                        aria-hidden="true"
                        className="nhm-dropdown--panel"
                        role="presentation"
                        tabIndex="-1"
                      >
                        <div
                          className="nhm-dropdown--body nhm-addon--dropdown nhm-addonvisual-position nhm-bodywidth nhm-addonhidden"
                          role="presentation"
                        >
                          <div className="nhm-dropdown--scrollable-container">
                            <div className="nhm-dropdown--scrollable-content">
                              <div
                                aria-label="Loading"
                                className="nhm-loader nhm-loader-medium nhm-loader-layout"
                                role="progressbar"
                              >
                                <div className="nhm-loader--dot" />
                                <div className="nhm-loader--dot" />
                                <div className="nhm-loader--dot" />
                              </div>
                              <div className="">
                                <div
                                  aria-label="Onboarding help options for new Xero users"
                                  className="nhm-switch-group"
                                />
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                <li
                  className="xnav-addon"
                  data-automationid="xrh-addon-connectedapps"
                  data-header-component="menu-parent"
                  tabIndex="-1"
                >
                  <button
                    aria-haspopup="true"
                    aria-label="Connected Apps"
                    className="xnav-header-button xnav-addon--iconbutton xnav-header--iconbutton xnav-focusable--parent"
                    data-automationid="xrh-addon-connectedapps-iconbutton"
                    data-header-component="menu-trigger"
                    title="Connected Apps"
                    type="button"
                  >
                    <div className="xnav-focusable--child xnav-iconwrapper" role="presentation">
                      <svg
                        className="xnav-icon xnav-icon-svg"
                        focusable="false"
                        height="20"
                        role="presentation"
                        viewBox="0 0 20 20"
                        width="20"
                      >
                        <path d="M4 2a2 2 0 11-4 0 2 2 0 014 0zm8 0a2 2 0 11-4 0 2 2 0 014 0zm6.001 2a2 2 0 100-4 2 2 0 000 4zm-14 6.001a2 2 0 11-4 0 2 2 0 014 0zm6 2a2 2 0 100-4 2 2 0 000 4zm10-2a2 2 0 11-4 0 2 2 0 014 0zm-18 10a2 2 0 100-4 2 2 0 000 4zm10-2a2 2 0 11-4 0 2 2 0 014 0zm6 2a2 2 0 100-4 2 2 0 000 4z" />
                      </svg>
                    </div>
                  </button>
                  <div
                    data-automationid="xrh-addon-connectedapps-body"
                    data-header-component="menu"
                    tabIndex="-1"
                  />
                </li>
                <li
                  className="xnav-addon xnav-addon-lastvisible"
                  data-automationid="xnav-addon-user"
                  data-header-component="menu-parent"
                  tabIndex="-1"
                >
                  <button
                    aria-haspopup="true"
                    aria-label="Test Person"
                    className="xnav-header-button xnav-addon--iconbutton xnav-header--iconbutton xnav-focusable--parent"
                    data-automationid="xnav-addon-user-iconbutton"
                    data-header-component="menu-trigger"
                    // eslint-disable-next-line react/no-access-state-in-setstate
                    onClick={() => this.setState({ navDDisOpen: !this.state.navDDisOpen })}
                    title="Test Person"
                    type="button"
                  >
                    <div className="xnav-focusable--child xnav-iconwrapper" role="presentation">
                      <abbr className="xnav-avatar xnav-avatar-color-7" role="presentation">
                        TP
                      </abbr>
                    </div>
                  </button>
                  <div
                    aria-hidden="true"
                    className={`xnav-dropdown-layout xnav-nav--dropdown xnav-dropdown-positionright ${
                      this.state.navDDisOpen && 'xnav-dropdown-is-open'
                    }`}
                    data-automationid="xnav-addon-user-body"
                    data-header-component="menu"
                  >
                    <div className="xnav-dropdown--mask" />
                    <div
                      aria-hidden="true"
                      className="xnav-dropdown--panel"
                      role="listbox"
                      tabIndex="-1"
                    >
                      <div className="xnav-dropdown--body" data-automationid="xnav-addon-user-body">
                        <ol className="xnav-verticalmenu" role="navigation">
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked ADDON: profile"
                              data-event-category="Nav"
                              data-menu-item-type="ADDON"
                              data-name="user-menu/profile"
                              data-on="click"
                              href="https://my.xero.com/Go/UserProfile"
                              tabIndex="-1"
                            >
                              <h4 className="xnav-verticalmenuitem--heading">Test Person</h4>
                              <span className="xnav-verticalmenuitem--subheading">
                                Edit profile
                              </span>
                            </a>
                          </li>
                          <li role="presentation">
                            <hr className="xnav-divider" />
                          </li>
                          <li className="xnav-verticalmenuitem">
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked ADDON: account"
                              data-event-category="Nav"
                              data-menu-item-type="ADDON"
                              data-name="user-menu/account"
                              data-on="click"
                              href="https://my.xero.com/Go/MyAccount"
                              tabIndex="-1"
                            >
                              Account
                            </a>
                          </li>
                          <li className="xnav-verticalmenuitem xnav-verticalmenuitem-righticon">
                            <a
                              aria-describedby="xnav-access-opens-new-window"
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked ADDON: xero-education"
                              data-event-category="Nav"
                              data-menu-item-type="ADDON"
                              data-name="user-menu/xero-education"
                              data-on="click"
                              href="https://central.xero.com/s/learning"
                              rel="nofollow noopener noreferrer"
                              tabIndex="-1"
                              target="_blank"
                            >
                              Learning (Xero Central)
                            </a>
                            <div className="xnav-verticalmenuitem--icon xnav-verticalmenuitem--icon-right xnav-iconwrapper">
                              <svg
                                className="xnav-icon xnav-icon-svg"
                                focusable="false"
                                height="12"
                                role="presentation"
                                viewBox="0 0 12 12"
                                width="12"
                              >
                                <path d="M10.75 2.75L7 6.5 5.5 5l3.75-3.75L8 0h4v4l-1.25-1.25zM6 0v1H1v10h10V6h1v4.91c0 .545-.5 1.09-1 1.09H1c-.5 0-1-.545-1-1.09l.01-9.82C0 .546.5 0 1 0h5z" />
                              </svg>
                            </div>
                          </li>
                          <li role="presentation">
                            <hr className="xnav-divider" />
                          </li>
                          <li className="xnav-verticalmenuitem xnav-verticalmenuitem-lefticon">
                            <div className="xnav-verticalmenuitem--icon xnav-iconwrapper">
                              <svg
                                className="xnav-icon xnav-icon-svg"
                                focusable="false"
                                height="17"
                                role="presentation"
                                viewBox="0 0 12 17"
                                width="12"
                              >
                                <path d="M2 7V4c0-4 4-4 4-4s4 0 4 4v3h1c1 0 1 1 1 1v8s0 1-1 1H1c-1 0-1-1-1-1V8s0-1 1-1h1zm2 0h4V4c0-2-2-2-2-2S4 2 4 4v3zm2 6a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                              </svg>
                            </div>
                            <a
                              className="xnav-verticalmenuitem--body"
                              data-event-action="Clicked ADDON: log-out"
                              data-event-category="Nav"
                              data-menu-item-type="ADDON"
                              data-name="user-menu/log-out"
                              data-on="click"
                              href="https://go.xero.com/logout"
                              tabIndex="-1"
                            >
                              Log out
                            </a>
                          </li>
                        </ol>
                      </div>
                    </div>
                  </div>
                </li>
                <li aria-hidden="true" className="xnav-addonscriptcontainer xnav-u-hidden">
                  <script
                    async=""
                    src="https://edge.xero.com/business/search/1.11.1/insert-iframe-min.js"
                  />
                  <script
                    async=""
                    src="https://edge.xero.com/platform/postoffice/prod/11.0.43/postoffice.js"
                  />
                  <script
                    async=""
                    src="https://edge.xero.com/platform/helpnavmenu/1.14.1/index.js"
                  />
                  <script
                    async=""
                    src="https://edge.xero.com/platform/applauncher/prod/1.0.110/applauncher.js"
                  />
                  <script
                    async=""
                    src="https://edge.xero.com/platform/helpmenuaddonlegacydependencies/1.0.5/helplegacydeps.js"
                  />
                </li>
              </ol>
            </div>
            <span className="xnav-u-hidden-visually">Current page</span>
            <span className="xnav-u-hidden-visually" id="xnav-access-opens-new-window">
              Opens in new window
            </span>
          </header>
        </div>
      </>
    );
  }
}

export default Example;
