import React, { Component } from 'react';

class Example extends Component {
  state = { navDDisOpen: false };

  // This is the rendered html of the current navigation, as generated by the SPA boilerplate as of Sept 3, 2021.
  // We will drop it here directly, along with the related stylesheet, for the purposes of testing.
  render() {
    return (
      <>
        <link href="https://edge.xero.com/platform/header/4.10.0/header.min.css" rel="stylesheet" />
        <div id="shell-nav">
          <header
            className="xrh-header xrh-header-business xrh-header-wide"
            data-automationid="xrh-header-container"
            role="banner"
          >
            <div className="xrh-header--main">
              <div
                className="xrh-appmenucontainer"
                data-header-component="menu-parent"
                tabIndex="-1"
              >
                <button
                  className="xrh-button xrh-appbutton xrh-appbutton-is-active"
                  data-header-component="menu-trigger"
                  id="navMenu"
                  // eslint-disable-next-line react/no-access-state-in-setstate
                  onClick={() => this.setState({ navDDisOpen: !this.state.navDDisOpen })}
                  type="button"
                >
                  <div className="xrh-appbutton--body">
                    <span className="xrh-appbutton--text">Hornblower Enterprises</span>
                  </div>
                </button>
                <div
                  className="xrh-appmenu xrh-appmenu-business xrh-appmenu-wide"
                  data-header-component="menu"
                >
                  <div className="xrh-appmenu--mask xrh-appmenu--mask-is-active" />
                  <div
                    className={`xrh-appmenu--body ${
                      this.state.navDDisOpen && 'xrh-appmenu--body-is-open'
                    }`}
                    tabIndex="-1"
                  >
                    <ul className="xrh-verticalmenu xrh-appmenu--verticalmenu">
                      <li className="xrh-verticalmenuitem">
                        <button
                          className="xrh-button xrh-verticalmenuitem--body xrh-verticalmenuitem--body-blue"
                          data-navigation-id="xrh-changeorgbutton"
                          tabIndex="-1"
                          type="button"
                        >
                          Change organisation
                        </button>
                      </li>
                    </ul>
                    <hr className="xrh-divider" />
                    <div className="xrh-appmenuheader">
                      <abbr
                        className="xrh-avatar xrh-avatar-large xrh-avatar-color-6 xrh-avatar-business"
                        role="presentation"
                      >
                        HE
                      </abbr>
                      <div className="xrh-appmenu--headings">
                        <span className="xrh-appmenu--heading" title="Hornblower Enterprises">
                          Hornblower Enterprises
                        </span>
                        <span className="xrh-appmenu--subheading">Practice Force One</span>
                      </div>
                    </div>
                    <div>
                      <ol className="xrh-verticalmenu" role="navigation">
                        <li className="xrh-verticalmenuitem">
                          <a
                            className="xrh-verticalmenuitem--body"
                            data-event-action="Clicked APP_MENU: xrh-secondaryappmenu-Organisation settings"
                            data-event-category="Nav"
                            data-menu-item-type="APP_MENU"
                            data-navigation-id="xrh-secondaryappmenu-Organisation settings"
                            data-on="click"
                            href="#org-settings"
                            tabIndex="-1"
                          >
                            Organisation settings
                          </a>
                        </li>
                        <li className="xrh-verticalmenuitem">
                          <a
                            className="xrh-verticalmenuitem--body"
                            data-event-action="Clicked APP_MENU: xrh-secondaryappmenu-Files"
                            data-event-category="Nav"
                            data-menu-item-type="APP_MENU"
                            data-navigation-id="xrh-secondaryappmenu-Files"
                            data-on="click"
                            href="#files"
                            tabIndex="-1"
                          >
                            Files
                          </a>
                        </li>
                      </ol>
                    </div>
                    <hr className="xrh-divider" />
                    <div className="xrh-appmenu--otherapps">
                      <ol className="xrh-verticalmenu" role="navigation">
                        <li className="xrh-verticalmenuitem xrh-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xrh-access-opens-new-window"
                            className="xrh-verticalmenuitem--body"
                            data-event-action="Clicked OTHER_APP: xrh-otherappsmenu-Workflow Max"
                            data-event-category="Nav"
                            data-menu-item-type="OTHER_APP"
                            data-navigation-id="xrh-otherappsmenu-Workflow Max"
                            data-on="click"
                            href="https://workflowmax.com"
                            rel="noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            Workflow Max
                          </a>
                          <div className="xrh-verticalmenuitem--icon xrh-verticalmenuitem--icon-right xrh-iconwrapper" />
                        </li>
                        <li className="xrh-verticalmenuitem xrh-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xrh-access-opens-new-window"
                            className="xrh-verticalmenuitem--body"
                            data-event-action="Clicked OTHER_APP: xrh-otherappsmenu-Workpapers"
                            data-event-category="Nav"
                            data-menu-item-type="OTHER_APP"
                            data-navigation-id="xrh-otherappsmenu-Workpapers"
                            data-on="click"
                            href="https://workpapers.xero.com"
                            rel="noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            Workpapers
                          </a>
                          <div className="xrh-verticalmenuitem--icon xrh-verticalmenuitem--icon-right xrh-iconwrapper" />
                        </li>
                        <li className="xrh-verticalmenuitem xrh-verticalmenuitem-righticon">
                          <a
                            aria-describedby="xrh-access-opens-new-window"
                            className="xrh-verticalmenuitem--body"
                            data-event-action="Clicked OTHER_APP: xrh-otherappsmenu-XeroHQ"
                            data-event-category="Nav"
                            data-menu-item-type="OTHER_APP"
                            data-navigation-id="xrh-otherappsmenu-XeroHQ"
                            data-on="click"
                            href="https://hq.xero.com"
                            rel="noopener noreferrer"
                            tabIndex="-1"
                            target="_blank"
                          >
                            XeroHQ
                          </a>
                          <div className="xrh-verticalmenuitem--icon xrh-verticalmenuitem--icon-right xrh-iconwrapper" />
                        </li>
                      </ol>
                    </div>
                  </div>
                </div>
              </div>
              <div className="xrh-u-hidden xrh-pagetitlewrapper">
                <span className="xrh-pagetitle">App</span>
              </div>
              <ol
                className="xrh-tabgroup xrh-tabgroup-layout xrh-navigation xrh-header-background-color"
                role="navigation"
              >
                <li className="xrh-tab" tabIndex="-1">
                  <a
                    className="xrh-focusable xrh-tab--body"
                    data-event-action="Clicked NAVIGATION: test-application"
                    data-event-category="Nav"
                    data-header-component="menu-trigger"
                    data-menu-item-type="NAVIGATION"
                    data-navigation-id="test-application"
                    data-on="click"
                    href="/"
                    tabIndex="0"
                  >
                    App
                  </a>
                </li>
              </ol>
              <ol className="xrh-addons xrh-header-background-color">
                <li
                  className="xrh-addon xrh-addon-alwaysvisible"
                  data-automationid="xrh-addon-user"
                  data-header-component="menu-parent"
                  tabIndex="-1"
                >
                  <button
                    aria-haspopup="true"
                    aria-label="Lion Ted"
                    className="xrh-button xrh-addon--iconbutton xrh-header--iconbutton xrh-focusable--parent"
                    data-automationid="xrh-addon-user-iconbutton"
                    data-header-component="menu-trigger"
                    // eslint-disable-next-line react/no-access-state-in-setstate
                    onClick={() => this.setState({ navDDisOpen: !this.state.navDDisOpen })}
                    tabIndex="0"
                    title="Lion Ted"
                    type="button"
                  >
                    <div className="xrh-focusable--child xrh-iconwrapper" role="presentation">
                      <abbr className="xrh-avatar xrh-avatar-color-7" role="presentation">
                        LT
                      </abbr>
                    </div>
                  </button>
                  <div
                    aria-hidden="true"
                    className={`xrh-dropdown-layout xrh-addon--dropdown xrh-dropdown-positionright ${
                      this.state.navDDisOpen && 'xrh-dropdown-is-open'
                    }`}
                    data-automationid="xrh-addon-user-body"
                    data-header-component="menu"
                  >
                    <div className="xrh-dropdown--mask" />
                    <div
                      aria-hidden="true"
                      className="xrh-dropdown--panel"
                      role="listbox"
                      tabIndex="-1"
                    >
                      <div className="xrh-dropdown--body" data-automationid="xrh-addon-user-body">
                        <ol className="xrh-verticalmenu" role="navigation">
                          <li className="xrh-verticalmenuitem">
                            <a
                              className="xrh-verticalmenuitem--body"
                              data-event-action="Clicked ADDON: xrh-Edit profile"
                              data-event-category="Nav"
                              data-menu-item-type="ADDON"
                              data-navigation-id="xrh-Edit profile"
                              data-on="click"
                              href="#edit-profile"
                              tabIndex="-1"
                            >
                              Edit profile
                            </a>
                          </li>
                          <li className="xrh-verticalmenuitem xrh-verticalmenuitem-lefticon xrh-verticalmenuitem-righticon">
                            <div className="xrh-verticalmenuitem--icon xrh-iconwrapper" />
                            <a
                              aria-describedby="xrh-access-opens-new-window"
                              className="xrh-verticalmenuitem--body"
                              data-event-action="Clicked ADDON: xrh-Xero U"
                              data-event-category="Nav"
                              data-menu-item-type="ADDON"
                              data-navigation-id="xrh-Xero U"
                              data-on="click"
                              href="#education"
                              rel="noopener"
                              tabIndex="-1"
                              target="_blank"
                            >
                              Xero U
                            </a>
                            <div className="xrh-verticalmenuitem--icon xrh-verticalmenuitem--icon-right xrh-iconwrapper" />
                          </li>
                          <li role="presentation">
                            <hr className="xrh-divider" />
                          </li>
                          <li className="xrh-verticalmenuitem xrh-verticalmenuitem-lefticon">
                            <div className="xrh-verticalmenuitem--icon xrh-iconwrapper" />
                            <a
                              className="xrh-verticalmenuitem--body"
                              data-event-action="Clicked ADDON: xrh-logout"
                              data-event-category="Nav"
                              data-menu-item-type="ADDON"
                              data-navigation-id="xrh-logout"
                              data-on="click"
                              href="#logout"
                              tabIndex="-1"
                            >
                              Logout
                            </a>
                          </li>
                        </ol>
                      </div>
                    </div>
                  </div>
                </li>
                <li aria-hidden="true" className="xrh-addonscriptcontainer xrh-u-hidden" />
              </ol>
            </div>
            <span className="xrh-u-hidden-visually" id="xrh-access-currently-selected-nav-item">
              Current page
            </span>
            <span className="xrh-u-hidden-visually" id="xrh-access-opens-new-window">
              Opens in new window
            </span>
          </header>
        </div>
      </>
    );
  }
}

export default Example;
