import React from 'react';

interface BaseProps {
  children?: React.ReactNode;
  /**
   * Class names to be added to the field wrapper element.
   */
  fieldClassName?: string;
  /**
   * Hint message to show under the input.
   */
  hintMessage?: React.ReactNode;
  /**
   * Whether to use the field layout classes.
   */
  isFieldLayout?: boolean;
  /**
   * Whether this will be used to wrap multple controls with their own labels.
   */
  isGroup?: boolean;
  /**
   * Whether the current input value is invalid.
   */
  isInvalid?: boolean;
  /**
   * Class names to add to the label.
   */
  labelClassName?: string;
  /**
   * Function to call on click inside the control.
   */
  onClick?: React.MouseEventHandler<HTMLDivElement>;
  /**
   * Function to call on keydown inside the control.
   */
  onKeyDown?: React.KeyboardEventHandler<HTMLDivElement>;
  qaHook?: string;
  /**
   * Validation message to show under the input if `isInvalid` is `true`.
   */
  validationMessage?: React.ReactNode;
  /**
   * IDs generated by `generateIds` and passed in from the parent component.
   */
  wrapperIds: {
    control?: string;
    label?: string;
    message?: string;
  };
}
interface VisibleLabelProps {
  /**
   * Should label be applied as an `aria-label`, rather than being visibly displayed.
   */
  isLabelHidden?: false;
  /**
   * Label to show above the input.
   */
  label?: React.ReactNode;
}
interface HiddenLabelProps {
  /**
   * Should label be applied as an `aria-label`, rather than being visibly displayed.
   */
  isLabelHidden: true;
  /**
   * Label to be used for the `aria-label`.
   */
  label: string;
}

type LabelProps = HiddenLabelProps | VisibleLabelProps;
type Props = BaseProps & LabelProps;

export default class XUIControlWrapper extends React.PureComponent<Props> {}
