export const englishMonths = [
	'January',
	'February',
	'March',
	'April',
	'May',
	'June',
	'July',
	'August',
	'September',
	'October',
	'November',
	'December',
];

export const customClassNames = {
	container: 'xui-datepicker',
	interactionDisabled: 'xui-is-disabled',
	navBar: 'xui-datepicker--header',
	navButtonPrev: 'xui-datepicker--arrow-icon',
	navButtonNext: 'xui-datepicker--arrow-icon',
	month: 'xui-datepicker--body',
	caption: '',
	weekdays: '',
	weekdaysRow: 'xui-datepicker--weekdays',
	weekday: 'xui-datepicker--weekday',
	body: '',
	week: 'xui-datepicker--week',
	day: 'xui-datepicker--day',
	today: 'xui-datepicker--day-is-today',
	selected: 'xui-datepicker--day-is-selected',
	outside: 'xui-datepicker--day-is-othermonth',
	disabled: 'xui-datepicker--day-is-disabled',
};
