name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'build_and_test'
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['14.2']
    steps:
      - name: Select Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
