name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['14.2']
        swift: ['5.7']
    steps:
      - name: Set up Swift ${{ matrix.swift }}
        uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Select Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: actions/checkout@v3
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}
      - name: Test
        run: swift test
