name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  test:
    name: Test (swift-${{ matrix.swift }}, xcode-${{ matrix.xcode }})
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ['14.3']
        swift: ['5.8']
    steps:
      - name: Setup Swift ${{ matrix.swift }}
        uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Select Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: actions/checkout@v3
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}
      - name: Get swift version
        run: swift --version
      - name: Test
        run: swift test

  test_ubuntu:
    name: Test (swift-${{ matrix.swift }}, ${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-20.04]
        swift: ['5.8']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift ${{ matrix.swift }}
        uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test
