name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  test:
    name: Test (Swift ${{ matrix.swift }}, Xcode ${{ matrix.xcode }})
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ['14.2']
        swift: ['5.7']
    steps:
      - name: Select Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
